### ISSUE TITLE
validate-example: when no errors are found, it's hard to differentiate whether the examples validation happened successfully or no examples were validated

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#100]
I believe we're outputting the exact same message today when no validation is done and when all validation is green. It'd be good to differentiate these cases, maybe showing how many examples were validated.

**Comment by amarzavery** [comment]
When we started this project, we explicitly chose to can the no x-ms-examples found error message as that was a noise. Looks like now the situation is different. I agree we should enable this again and start providing a basic coverage of the number of operations provided with x-ms-examples or with examples in spec. While providing this coverage we need to make sure that we also provide coverage for minimum (just the required properties) and maximum (all the properties (required + optional).

**Comment by amarzavery** [comment]
This logic needs to be modified https://github.com/Azure/openapi-validation-tools/blob/master/lib/validators/specValidator.js#L518

**Comment by amarzavery** [comment]
Uncomment this code and we will see the errors for x-ms-example not found https://github.com/Azure/openapi-validation-tools/blob/master/lib/validators/specValidator.js#L404
