### ISSUE TITLE
Re-enable AdditionalProperties validation in RPaaS

### ISSUE THREAD

**Issue by wwendyc** [Azure/oav#1013]
When the additionalProperties linter rule was first introduced, it broke some partner services and had to be rolled back.

Since then, RPaaS has worked with partners flagged for the issue to fix their specs.

Currently, it's being emitted as a warning instead of an error. The request is to re-enable the validation in RPaaS to ensure compliance and prevent new RPs from unknowingly violating the rule which could result in service outages when it's turned on in the future.

**Comment by scbedd** [comment]
This was completed in #1027 and released as oav `3.3.8` on npmjs.org.
