### ISSUE TITLE
`oav` not properly honoring `collectionFormat` when comparing types

### ISSUE THREAD

**Issue by scbedd** [Azure/oav#1020]
We have an easy repro:

[specification](https://github.com/Azure/azure-rest-api-specs/blob/f68799746cf80556cc460dc08ae4e3b741274d1c/specification/maps/data-plane/Creator/preview/2.0/wfs.json#L92:16)
[example](https://github.com/Azure/azure-rest-api-specs/blob/f68799746cf80556cc460dc08ae4e3b741274d1c/specification/maps/data-plane/Creator/preview/2.0/examples/wfs/WFS_GetFeatures.json?short_path=baadf9b#L8:13)

When `collectionFormat` is set to `csv`, an incoming property must have _postprocessing_ done to it prior to actually checking the types.

For instance, in this case, the property with collectionFormat of `csv` is being treated as a string, instead of a number. Somewhere we are failing to coerce the value of `"1.0, 2.0, 3.0, 4.0"` to `[1.0, 2.0, 3.0, 4.0]`.

The failure looks like:

![image](https://github.com/Azure/oav/assets/45376673/884a0697-79c0-4c8a-81b3-efc806dc32aa)

We should definitely not be false positive erroring on this.

**Comment by mikekistler** [comment]
This does not seem like a problem in oav to me.  oav is flagging a parameter defined as an array whose value (in the example file) is not an array. That seems like the correct behavior to me.

It is true that the array, _when serialized into the query string_ will be a string -- but that's true for all parameters types.

**Comment by scbedd** [comment]
We chatted offline and I agree, this issue was founded based on my misinterpretation of the spec. Closing.
