### ISSUE TITLE
Update oav generated sample values for password to use a secret placeholder instead of a random string that looks like it could be a password

### ISSUE THREAD

**Issue by qiaozha** [Azure/oav#1041]
https://github.com/Azure/azure-rest-api-specs/pull/29673#discussion_r1665305465 service team is using oav to generate the rest api examples, but codegen will use those samples to generate the SDK sample, which causes sdk credential scan failure https://github.com/Azure/azure-sdk-for-js/issues/30232

**Comment by weshaggard** [comment]
Let's try to use a standard placeholder for the generated strings that look like they could be a valid secret.

**Comment by scbedd** [comment]
@weshaggard I have moved this issue to `oav` repo. This is a fairly minor change that is fairly low risk. I think I will just execute on this if you don't have any protests.

**Comment by weshaggard** [comment]
Sounds good @scbedd

**Comment by RickWinter** [comment]
@scbedd This is in backlog, is it being actively worked on? Having checks for this in specs could greatly reduce the MSRC false positives noise.

/cc: @weshaggard , @joshfree

**Comment by scbedd** [comment]
> This is in backlog, is it being actively worked on? 

I mean...I got the thumbs up from Wes to go ahead 8 hours ago. I was intending on picking it up tomorrow.

> Having checks for this in specs could greatly reduce the MSRC false positives noise.

What do you mean? This change is to cause oav to generate password fields with non-random characters. I'm not necessarily throwing away ALL random character generation.

Are you asking for something beyond what this issue covers? Just trying to understand if I'm missing something.

**Comment by RickWinter** [comment]
Nope you aren't missing anything. The goal is to avoid having passwords that look real which is what results in the false positives.

**Comment by scbedd** [comment]
Now available on npmjs.org:

![image](https://github.com/user-attachments/assets/12b9acc4-2ce7-4a2d-9f8b-3fb1f675f619)

If there are additional fields that we want to continue to add, we'll account for those in followp-up versions.
