### ISSUE TITLE
Use Linux line endings?

### ISSUE THREAD

**Issue by jianghaolu** [Azure/oav#109]
Running on macOS 10.12.4:

```bash
$ oav
env: node\r: No such file or directory
```

Running `:set ff=unix` in vim for `/usr/local/bin/oav` fixes the issue.

**Comment by amarzavery** [comment]
thanks for reporting. We fixed this in 0.3.0 version of oav. This PR https://github.com/Azure/oav/pull/110 fixes it.

**Comment by jianghaolu** [comment]
Thanks!
