### ISSUE TITLE
Type "integer" in the query parameter is not validated correctly

### ISSUE THREAD

**Issue by vishrutshah** [Azure/oav#111]
PR https://github.com/Azure/azure-rest-api-specs/pull/1144
CI: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/224181499#L1095

Swagger Model: https://github.com/cohnmarc/azure-rest-api-specs/blob/c9316f904cf839c929559256bbb3f3fe56bba0b2/arm-advisor/2017-04-19/swagger/advisor.json#L77
```json5
"/subscriptions/{subscriptionId}/providers/Microsoft.Advisor/recommendations": {
			"get": {
				"tags": ["GetRecommendations"],
				"description": "Obtains cached recommendations for a subscription. The recommendations are generated or computed by invoking generateRecommendations.",
				"operationId": "Recommendations_List",
				"parameters": [{
						"$ref": "#/parameters/subscriptionIdParameter"
					}, {
						"$ref": "#/parameters/apiVersionParameter"
					}, {
						"name": "$filter",
						"in": "query",
						"description": "The filter to apply to the recommendations.",
						"required": false,
						"type": "string"
					}, {
						"name": "$top",
						"in": "query",
						"description": "The number of recommendations per page if a paged version of this API is being used.",
						"required": false,
						"type": "integer"
					},
...		
```

x-ms-example: https://github.com/cohnmarc/azure-rest-api-specs/blob/c9316f904cf839c929559256bbb3f3fe56bba0b2/arm-advisor/2017-04-19/examples/ListRecommendations.json
```json5
{
  "parameters": {
    "subscriptionId": "subscriptionId",
    "$top": 10,
    "api-version": "2017-04-19"
  },
  "responses": {
    "200": {
      "body": {
```
Investigation:
Looks like if someone changes x-ms-example with `"$top": "10"` then error disappears. Looks like issue at [value = _.get(req.query, this.name);](https://github.com/amarzavery/sway/blob/validation/lib/types/parameter.js#L178) returns an `object` type when provided example has `"$top": "10"` while returns string when example has `"$top": 10`

**Comment by amarzavery** [comment]
fixed.
