### ISSUE TITLE
Null values for string fields are not supported. Fails with message message: 'Expected type string but found type null'

### ISSUE THREAD

**Issue by avneeshrai** [Azure/oav#116]
**w.r.t PR https://github.com/Azure/azure-rest-api-specs/pull/1209
For operation ID: ReplicationFabrics_Get**

**For example:**
{
  "parameters": {
    "fabricName": "cloud1",
    "api-version": "2016-08-10",
    "resourceName": "vault1",
    "resourceGroupName": "resourceGroupPS1",
    "subscriptionId": "c183865e-6077-46f2-a3b1-deb0f4f4650a"
  },
  "responses": {
    "200": {
      "body": {
        "name": "cloud1",
        "type": "Microsoft.RecoveryServices/vaults/replicationFabrics",
        "id": "/Subscriptions/c183865e-6077-46f2-a3b1-deb0f4f4650a/resourceGroups/resourceGroupPS1/providers/Microsoft.RecoveryServices/vaults/vault1/replicationFabrics/cloud1",
        "properties": {
          "friendlyName": "cloud1",
          "encryptionDetails": {
            "kekState": "None",
            "kekCertThumbprint": null
          },
          "rolloverEncryptionDetails": {
            "kekState": "None",
            "kekCertThumbprint": null
          },
          "internalIdentifier": "6d224fc6-f326-5d35-96de-fbf51efb3179",
          "bcdrState": "Valid",
          "customDetails": {
            "instanceType": "HyperVSite"
          },
          "healthErrorDetails": [],
          "health": "Normal"
        }
      }
    }
  }
}

**Validator fails with:**
{ code: 'RESPONSE_VALIDATION_ERROR',
message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Gets the details of a Site." in operation "ReplicationFabrics_Get".',
innerErrors:
[ { code: 'INVALID_RESPONSE_BODY',
errors:
[ { code: 'INVALID_TYPE',
params: [ 'string', 'null' ],
message: 'Expected type string but found type null',
path:
[ 'properties',
'rolloverEncryptionDetails',
'kekCertThumbprint' ],
description: 'Gets or sets the key encryption key certificate thumbprint.' },
{ code: 'INVALID_TYPE',
params: [ 'string', 'null' ],
message: 'Expected type string but found type null',
path: [ 'properties', 'encryptionDetails', 'kekCertThumbprint' ],
description: 'Gets or sets the key encryption key certificate thumbprint.' } ],
message: 'Invalid body: Value failed JSON Schema validation',
path: [] } ] }

**Comment by veronicagg** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/798

**Comment by veronicagg** [comment]
https://github.com/Azure/oav/issues/155
