### ISSUE TITLE
Polymorphic fields are not supported and validator fails with message: "Additional properties not allowed:"

### ISSUE THREAD

**Issue by avneeshrai** [Azure/oav#117]
**w.r.t PR Azure/azure-rest-api-specs#1209
For operation ID: ReplicationPolicies_Get**

**For example:**
{
  "parameters": {
    "policyName": "protectionprofile1",
    "api-version": "2016-08-10",
    "resourceName": "vault1",
    "resourceGroupName": "resourceGroupPS1",
    "subscriptionId": "c183865e-6077-46f2-a3b1-deb0f4f4650a"
  },
  "responses": {
    "200": {
      "body": {
        "id": "/Subscriptions/c183865e-6077-46f2-a3b1-deb0f4f4650a/resourceGroups/resourceGroupPS1/providers/Microsoft.RecoveryServices/vaults/vault1/replicationPolicies/protectionprofile1",
        "name": "protectionprofile1",
        "type": "Microsoft.RecoveryServices/vaults/replicationPolicies",
        "properties": {
          "friendlyName": "protectionprofile1",
          "providerSpecificDetails": {
            "instanceType": "HyperVReplicaAzure",
            "recoveryPointHistoryDurationInHours": 1,
            "applicationConsistentSnapshotFrequencyInHours": 0,
            "replicationInterval": 30,
            "encryption": "Disabled",
            "activeStorageAccountId": "/subscriptions/c183865e-6077-46f2-a3b1-deb0f4f4650a/resourceGroups/siterecoveryprod1/providers/Microsoft.Storage/storageAccounts/storavrai"
          }
        }
      }
    }
  }
}

**Validator fails with:**
{ code: 'RESPONSE_VALIDATION_ERROR',
message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Gets the details of a Site." in operation "ReplicationFabrics_Get".',
innerErrors:
[ { code: 'INVALID_RESPONSE_BODY',
errors:
[ { code: 'INVALID_TYPE',
params: [ 'string', 'null' ],
message: 'Expected type string but found type null',
path:
[ 'properties',
'rolloverEncryptionDetails',
'kekCertThumbprint' ],
description: 'Gets or sets the key encryption key certificate thumbprint.' },
{ code: 'INVALID_TYPE',
params: [ 'string', 'null' ],
message: 'Expected type string but found type null',
path: [ 'properties', 'encryptionDetails', 'kekCertThumbprint' ],
description: 'Gets or sets the key encryption key certificate thumbprint.' } ],
message: 'Invalid body: Value failed JSON Schema validation',
path: [] } ] }

**Comment by amarzavery** [comment]
This issue has been fixed. Validation of polymorphic properties is now supported.
