### ISSUE TITLE
oav reports error for example validation when spec uses x-ms-paths 

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#140]
Error:
error: Found errors in validating the request for x-ms-example "Sets the owner of a file or directory" in operation "FileSystem_SetPermission".:

{ code: 'REQUEST_VALIDATION_ERROR',
  message: 'Found errors in validating the request for x-ms-example "Sets the owner of a file or directory" in operation "FileSystem_SetPermission".',
  innerErrors:
   [ { code: 'INVALID_REQUEST_PARAMETER',
       errors:
        [ { code: 'REQUIRED',
            message: 'Value is required but was not provided',
            path:
             [ 'paths',
               '/webhdfs/v1/{path}?op=SETPERMISSION',
               'put',
               'parameters',
               '0' ] } ],
       in: 'path',
       message: 'Invalid parameter (path): Value is required but was not provided',
       name: 'path',
       path: { '$ref': '$["innerErrors"][0]["errors"][0]["path"]' } } ] }

Based on investigation '?' is confusing the model validation at:
https://github.com/amarzavery/sway/blob/validation/lib/types/parameter.js#L164

Instead of reaching that point with '?' which is basically being included because of "x-ms-paths" and its "autorest-isms", we can replace '?' with '/' for the purposes of example validation when unifying x-ms-paths. This is also a local workaround to validate examples, until this fix is done.

**Comment by veronicagg** [comment]
we should check that this doesn't cause a problem for the live-validation switch

**Comment by amarzavery** [comment]
fixed.
