### ISSUE TITLE
oav uses lodash but doesn't reference it!

### ISSUE THREAD

**Issue by olydis** [Azure/oav#141]
`lib/validators/liveValidator.js` imports `lodash` but it's not a reference of this package. Note that there's virtually no reason to even use lodash in that file, so I'd almost fix this by not using lodash in the first place 😄

**Comment by amarzavery** [comment]
It is now being used at different places in the file. Hence closing this.

**Comment by olydis** [comment]
@amarzavery but is there a dependency to it now??? At least https://github.com/Azure/oav/blob/master/package.json doesn't mention it, but I'm not a lodash expert. I opened this issue because I was *not able to use oav* out of the box when installing it - this ruled it out as an extension to AutoRest.

**Comment by amarzavery** [comment]
That is interesting. There should have been a dependency to loadash. Looks like something that oav depends on, transitively depends on loadash. Newer versions of npm will flatten all the dependencies and by the virtue of which loadash is present as a top level package in the node_modules folder. Hence never had issues. I will add a dependency to loadash in the currenty open PR #162
