### ISSUE TITLE
Polymorphic operation validation fails - 

### ISSUE THREAD

**Issue by vishrutshah** [Azure/oav#142]
```
D:\Repos\oav>oav validate-example "C:\\Users\\vissha\\Downloads\\2017-03-01-preview\\swagger\\datafactory.json" -o Pipelines_ListByFactory
error: Found errors in validating the response with statusCode "200" for x-ms-example "Pipelines_ListByFactory" in operation "Pipelines_ListByFactory".:

{ code: 'RESPONSE_VALIDATION_ERROR',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Pipelines_ListByFactory" in operation "Pipelines_ListByFactory".',
  innerErrors:
   [ { code: 'INVALID_RESPONSE_BODY',
       errors:
        [ { code: 'OBJECT_ADDITIONAL_PROPERTIES',
            params: [ [ 'typeProperties' ] ],
            message: 'Additional properties not allowed: typeProperties',
            path:
             [ 'value',
               '0',
               'properties',
               'activities',
               '0',
               'typeProperties',
               'activities',
               '0' ],
            description: 'A pipeline activity.' } ],
       message: 'Invalid body: Additional properties not allowed: typeProperties',
       path: [] } ] }
```
Working `amarzavery/sway` commit: [3429105b265070d9fed0033528e02894a2540733](https://github.com/amarzavery/sway/tree/3429105b265070d9fed0033528e02894a2540733)

**Comment by vishrutshah** [comment]
Child Activity types are not recognized for Container ..

This need to change the logic. We should traverse the `x-ms-examples` and then match it against the swagger schema to support multi-level polymorphic examples.

**Comment by amarzavery** [comment]
This issue can be resolved by processing the model with discriminator property. If we replace all the references to the parent model with a oneOf array containing references to the parent model and all its child models and modify the discriminator property in the child models by making it a constant (enum with one value) with the value expected for that model type on the wire (model name or whatever is indicated by x-ms-discriminator-value). 
 

For example: There is a model named "Animal" with a discriminator as "animalType". Models like "Cat", "Dog", Tiger" are children (having "allof": [ { "$ref": "#/definitions/Animal" } ] on) of "Animal" in the swagger spec. 

 - We will have to replace all the locations in the swagger spec that have a reference to the
 parent model "Animal" ("$ref": "#/definitions/Animal") with a oneOf reference 
 ```
 "oneOf": [ { "$ref": "#/definitions/Animal" }, { "$ref": "#/definitions/Cat" },  { "$ref": "#/definitions/Dog" }, { "$ref": "#/definitions/Tiger" }  ]
 ``` .
-  We need to make sure that we do not modify the allOf reference that a child model will have on it's parent. 

 - We will also add a constant value (name of that animal on the wire or the value provided by 
 "x-ms-discriminator-value") to the discrimiantor property "animalType" for each of the child models. 
 For example:  the Cat model's discriminator property will look like:
 ```
 "Cat": { "required": [ "animalType" ], "properties": { "animalType": { "type": "string", "enum": [ "Cat" ] },  . . } }
 ```.

**Comment by vishrutshah** [comment]
Here is the test against recent check-in would looks like for 

```
vishrut@visshamac oav (polymorphic-validation) $ node cli.js validate-example /Users/vishrut/git-repos/azure-rest-api-specs/specification/datafactory/resource-manager/Microsoft.DataFactory/2017-09-01-preview/datafactory.json -o Pipelines_ListByFactory
info: No Errors were found.
```

**Comment by vishrutshah** [comment]
Release version `0.4.15` to https://www.npmjs.com/package/oav

```
D:\Repos\azure-rest-api-specs>oav --version
0.4.15

D:\Repos\azure-rest-api-specs>oav validate-example D:\Repos\azure-rest-api-specs\specification\datafactory\resource-manager\Microsoft.DataFactory\2017-09-01-preview\datafactory.json -o Pipelines_ListByFactory
info: No Errors were found.
```
