### ISSUE TITLE
Make Model Validation Output Similar to Semantic and Linter Output

### ISSUE THREAD

**Issue by shawns1** [Azure/oav#148]
Model Validation format changes to improve data collection:
There are some validation output changes that would make data collection easier.  The primary issues when collecting data are that there isn’t a standard format for each error returned and that the json file is broken down by node names for the errors rather than something more generic like arrays like the Semantic validator output.  Examples of both outputs are below.
Currently linter and semantic validation:  It is an array of errors per spec
 
{
  "D:/workspace/azure-rest-api-specs-Validation/specification/advisor/resource-manager/Microsoft.Advisor/2016-07-12-preview/advisor.json": [
    {
      "type": "Warning",
      "code": "OperationIdNounVerb",
      "message": "Per the Noun_Verb convention for Operation Ids, the noun 'Recommendations' should not appear after the underscore. Note: If you have already shipped an SDK on top of this spec, fixing this warning may introduce a breaking change.",
      "id": "R1001",
      "validationCategory": "SDKViolation",
      "providerNamespace": "Microsoft.Advisor",
      "resourceType": "generateRecommendations",
      "sources": [
        "file:///D:/workspace/azure-rest-api-specs-Validation/specification/advisor/resource-manager/Microsoft.Advisor/2016-07-12-preview/advisor.json:51:4 ($.paths[\"/subscriptions/{subscriptionId}/providers/Microsoft.Advisor/generateRecommendations/{operationId}\"].get.operationId)"
      ]
    },
    {
      "type": "Error",
      "code": "BodyTopLevelProperties",
      "message": "Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity. Model definition 'SuppressionContract' has extra properties ['suppressionId,ttl'].",
      "id": "R3006",
      "validationCategory": "RPCViolation",
      "providerNamespace": null,
      "resourceType": null,
      "sources": [
        "file:///D:/workspace/azure-rest-api-specs-Validation/specification/advisor/resource-manager/Microsoft.Advisor/2016-07-12-preview/advisor.json:583:3 ($.definitions.SuppressionContract.properties)"
      ]
    }
  ],
  "D:/workspace/azure-rest-api-specs-Validation/specification/advisor/resource-manager/Microsoft.Advisor/2017-03-31/advisor.json": [
    {…
 
 
 
Modeler is based on node names which are mapped to object names when de-serializing.  
 
 
{
  "D:/workspace/azure-rest-api-specs-MValidation/node_modules/oav/test/swaggers/specification/resources/resource-manager/Microsoft.Resources/2016-09-01/resources.json": {
    "validityStatus": true,
    "operations": {
      "Deployments_Delete": {
        "x-ms-examples": {
          "error": {
            "code": "X-MS-EXAMPLE_NOTFOUND_ERROR",
            "message": "x-ms-example not found in Deployments_Delete."
          }
        }
      },
      "Deployments_CheckExistence": {
        "x-ms-examples": {
          "error": {
            "code": "X-MS-EXAMPLE_NOTFOUND_ERROR",
            "message": "x-ms-example not found in Deployments_CheckExistence."
          }
        }
      }…

 
Some span multiple nodes under the current.
 
    "validityStatus": false,
    "operations": {
      "AdminKeys_Get": {
        "x-ms-examples": {
          "error": {
            "code": "X-MS-EXAMPLE_NOTFOUND_ERROR",
            "message": "x-ms-example not found in AdminKeys_Get."
          }
        },
        "example-in-spec": {
          "isValid": true,
          "request": {
            "isValid": true
          },
          "responses": {
            "200": {
              "isValid": true,
              "result": "Response with statusCode \"200\" for example in spec for operation \"AdminKeys_Get\" is valid."
            }
          }
        }
      },
 
We need a simple view of the modeler based on the validator's format.

**Comment by veronicagg** [comment]
I think this may help https://github.com/Azure/autorest/pull/2479, we'll discuss it for next sprint planning and update this issue.

**Comment by veronicagg** [comment]
This has been addressed, @shawns1 if you have further feedback, please let me know. I'm going to open an issue the the couple of errors you reported on specific specs where the tool is throwing an exception.
