### ISSUE TITLE
When 'consumes application/json' is missing on a spec, the error for validate-example is not clear on action item

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#151]
I was inspecting a PR yesterday, the spec did not include "consumes": [ "application/json"], there were errors reported for each operation regarding content type, but it wasn't clear how to fix the problem. 
I assume the tool may be defaulting to some other format which is causing the error to occur. 
We may be able to change the default for us (since ARM specs consume/produce only application/json, or help with the error message (or documentation).

**Comment by mcardosos** [comment]
Now oav defaults to application/json
Fixed on https://github.com/Azure/oav/pull/192
