### ISSUE TITLE
[ApiManagement] Semantic validation fails when x-ms-example contains swagger response

### ISSUE THREAD

**Issue by vishrutshah** [Azure/oav#152]
CI: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/265745269#L3508

**Comment by veronicagg** [comment]
@amarzavery do you know if this has been addressed?

**Comment by amarzavery** [comment]
I think this is a non issue. The validator is failing correctly. The swagger spec does not have x-ms-enum defined as expected by our version of swagger schema https://github.com/Azure/autorest/blob/master/schema/swagger-extensions.json#L1485
