### ISSUE TITLE
Invalid ‘type’ are not recognized by the validation 

### ISSUE THREAD

**Issue by haricr** [Azure/oav#153]
Swagger Shared in : \\hari-desktop\2017-03-01-preview

API

My Input payload for validation

{
        "liveRequest": {
          "rawResponse": false,
          "queryString": {},
          "url": "https://management.azure.com/subscriptions/subcriptionID/resourcegroups/resourceGroup/providers/Microsoft.DataFactory/factories/factoryName/linkedServices/linkedServiceName?api-version=2017-03-01-preview",
          "method": "PUT",
          "headers": {
            "Content-Type": "application/json; charset=utf-8",
            "accept-language": "en-US",
            "x-ms-client-request-id": "81161439-5d0a-4f6c-a41d-08d20985bee7"
          },
          "body": {
                              "properties": {
                  "description": "Test",
                  "type": "123"
                              }
          }
        },
        "liveResponse": {
          "statusCode": "200",
          "body": {
          },
          "headers": {
            "content-type": "application/json"
          }
        }
      }

I am passing a invalid type but validation is returning success

{
    "requestValidationResult": {
        "successfulRequest": true,
        "operationInfo": [
            {
                "operationId": "LinkedServices_CreateOrUpdate",
                "apiVersion": "2017-03-01-preview"
            }
        ],
        "errors": []
    },
    "responseValidationResult": {
        "successfulResponse": false,
        "operationInfo": [
            {
                "operationId": "LinkedServices_CreateOrUpdate",
                "apiVersion": "2017-03-01-preview"
            }
        ],

**Comment by veronicagg** [comment]
@haricr Swagger is not accessible, if you can push it to a branch in your fork of the repo and send us the link, we could take a look. Also, which command are you using? thanks!

**Comment by veronicagg** [comment]
@haricr we haven't heard back, so closing the issue, if you add more info, please reopen. Thanks!
