### ISSUE TITLE
Validate examples reporting error when there are "/" values for path parameters

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#165]
Here's the example where this issue occurred: 
-	Swagger def of param: https://github.com/Azure/azure-rest-api-specs/pull/1648/files#diff-eb84d1cad45c568273be52d4cec4c047R33 
-	Example def with param: https://github.com/Azure/azure-rest-api-specs/pull/1648/files#diff-196fec1ea9372d75cba90e958b3ee8d1R3 
-	CI complaining about missing param: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/273126090#L859

https://github.com/Azure/azure-rest-api-specs/pull/1648

**Comment by veronicagg** [comment]
Error:

{ code: 'REQUEST_VALIDATION_ERROR',     id: 'OAV109',     message: 'Found errors in validating the request   for x-ms-example "EventSubscriptions_CreateForSubscription" in   operation "EventSubscriptions_Create".',     innerErrors:      [ { code: 'INVALID_REQUEST_PARAMETER',          errors:           [ { code:   'REQUIRED',                 message: 'Value is   required but was not provided',                 path:                  [ 'paths',                    '/{scope}/providers/Microsoft.EventGrid/eventSubscriptions/{eventSubscriptionName}',                    'put',                    'parameters',                    '0' ] } ],          in: 'path',          message: 'Invalid parameter (scope):   Value is required but was not provided',          name: 'scope',          path: { '$ref':   '$["innerErrors"][0]["errors"][0]["path"]' } },        { code:   'INVALID_REQUEST_PARAMETER',          errors:           [ { code:   'REQUIRED',                 message: 'Value is required but was not provided',                 path:                  [ 'paths',                    '/{scope}/providers/Microsoft.EventGrid/eventSubscriptions/{eventSubscriptionName}',                    'put',                    'parameters',                    '1' ] } ],          in: 'path',          message: 'Invalid parameter   (eventSubscriptionName): Value is required but was not provided',          name:   'eventSubscriptionName',          path: { '$ref':   '$["innerErrors"][1]["errors"][0]["path"]' } }   ] }
--

**Comment by amarzavery** [comment]
fixed.
