### ISSUE TITLE
Validate examples complains about invalid content type when there's no content type (since there's no body parameter)

### ISSUE THREAD

**Issue by olydis** [Azure/oav#167]
See https://github.com/kalyanaj/azure-rest-api-specs/blob/7902a2310bf5fd89d60e06a93c85383debcb1542/specification/eventgrid/resource-manager/Microsoft.EventGrid/2017-06-15-preview/examples/EventSubscriptions_GetFullUrlForResourceGroup.json
which is AFAIK a valid example for https://github.com/Azure/azure-rest-api-specs/pull/1648/files#diff-eb84d1cad45c568273be52d4cec4c047L221.

But oav [complains](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/274333724#L1320):
> message: 'Invalid Content-Type (application/json).  These are supported: ',

Note that that operation has declared an empty `consumes`, but that is fine, after all there is no body parameter.

**Comment by sergey-shandar** [comment]
Another example https://github.com/Azure/azure-rest-api-specs-pr/pull/221, https://travis-ci.com/Azure/azure-rest-api-specs-pr/jobs/93994593

Message

```
{ code: 'RESPONSE_VALIDATION_ERROR',
  id: 'OAV108',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "GetCopyrightBounding" in operation "GetCopyrightBounding".',
  innerErrors: 
   [ { code: 'INVALID_CONTENT_TYPE',
       message: 'Invalid Content-Type (application/octet-stream).  These are supported: ',
       path: [] } ] }
error: Found errors in validating the response with statusCode "400" for x-ms-example "GetCopyrightBounding" in operation "GetCopyrightBounding".:
```

**Comment by sergey-shandar** [comment]
Another one https://github.com/Azure/azure-rest-api-specs/pull/2130

**Comment by mcardosos** [comment]
Looks like it has been fixed in some provided examples already. Will be fully fixed with https://github.com/Azure/oav/pull/192
