### ISSUE TITLE
Evaluate making oav not require all response codes in one x-ms-example file

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#186]
Our current approach is not to have a request-response pair in the x-ms-example, but include one request example and all error codes with example responses. As we're doing model validation, it does not matter that the request does not correspond to the response. 
We've received feedback that this may be confusing and may not lead well to documentation. 
Our intention is not to validate correctness of the service, so we're not expected to know/validate whether the response corresponds to the data included in the request. 

At the moment we require all response codes from the spec to be included in the example. We could relax that requirement and accommodate for multiple files providing data for each response code separately.

FYI - @amarzavery @salameer @VipulM-MSFT

**Comment by amarzavery** [comment]
dupe #218
