### ISSUE TITLE
OAV is not taking missing discriminator value into account

### ISSUE THREAD

**Issue by mcardosos** [Azure/oav#187]
This issue https://github.com/Azure/autorest/issues/2715
Examples which are polymorphic, but missing the discriminator are being marked as errors.

**Comment by amarzavery** [comment]
Out of scope to handle this. We want to make sure that model validation is performed correctly.
Two scenarios:
- property marked as discriminator is present but has a value that maps to a model that is not defined in the spec. In the sdk we default to the immediate parent for [de]serialization. However, in the model validation that is not possible. We resolve allOf by composition and then resolve the references to the parent with a oneOf array containing reference to the parent and all its children. Thus the model needs to be exactly one of those. There is no way for us to say that if not found then default to parent. So these kind of errors need to be suppressed (if applicable).
- property marked as discriminator is a required property as per OAI 2.0. If this property is missing then it is an incorrect representation in the first place. It makes no sense for the model validator to handle such a scenario.

**Comment by veronicagg** [comment]
closing per explanation above.
