### ISSUE TITLE
Mistyped command is accepted with no error message

### ISSUE THREAD

**Issue by mboersma** [Azure/oav#190]
The correct command is `oav validate-example`, but if you mistakenly add an `s` to the end, it is accepted without complaint and appears to succeed:

```shell
$ oav --version
0.4.21
$ oav validate-example Microsoft.ContainerService/2017-01-31/containerService.json 
error:  Error: In operation "ContainerServices_List", exampleParameterValues cannot be null or undefined and must be of type "object" (A dictionary of key-value pairs of parameter-names and their values).
    at SpecValidator.validateRequest (/usr/local/lib/node_modules/oav/lib/validators/specValidator.js:566:13)
...
$ oav validate-examples Microsoft.ContainerService/2017-01-31/containerService.json 
$ echo $?
0
$ oav take-the-rest-of-the-day-off nonexistent.file
$ echo $?
0
```

This bug could lead someone astray for quite a while, since you might easily believe you typed the correct command, and the tool is telling you everything passed.

**Comment by amarzavery** [comment]
@mboersma - This has been fixed in 0.4.22. Please feel free to reopen this issue if the problem persists.

**Comment by mboersma** [comment]
@amarzavery I tested with 0.4.22 and everything works as expected now. Thanks again for pouncing on this bug!

**Comment by amarzavery** [comment]
@mboersma - We have also added a new command `oav generate-uml <spec-path>` that provides a class diagram of the model definitions in your swagger spec. You can find more information over [here](https://github.com/Azure/oav/releases/tag/oav-0.4.22). Hope you find it useful :).
