### ISSUE TITLE
Add validation for response headers. - Static validation of long running operations

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#20]
This includes validating the structure of the URL provided for polling and also the right kind of URL with the status code.

**Comment by amarzavery** [comment]
@veronicagg, @salameer @vishrutshah  - This would be a high priority IMO. We should also enforce service teams to provide the relevant headers (azure-asyncoperation, Location, retry-after, etc. ) in the initial response of long running operations.
If they are not present then oav can flag errors and make service teams provide those in examples

Benefits
1. We validate that the uri present in the response header has a valid structure. (Remember Redis cache forgot to add api-version in the Location header and then polling failed).
2. Doc team will be using the data from x-ms-examples for generating wire format. If these important headers are not present then the wireformat will be incomplete and customer will not get a complete picture from the REST API doc website.  
3. It becomes super easy for anyone to find out the polling mechanism by looking at the example. No need to look at different places to find out which mechanism is being used. 


To expand on this a little more:
- For long running operations we should have  a structure in x-m-examples that can provide data about polling operation. This will be very helpful for documentation and help us better understand issues when we see a bug in long running operation in any sdk.

```json5
{
  parameters: { . . . }, //current structure
  responses: { 
    202: {
      headers: {
        "azure-asyncoperation": "https://foobar....?api-version=zoomba", //missing info currently
        "retry-after": 20 //missing info currently
       }
    },
    . . .
  },  //current structure
  polling: {
    request-url: 'https://foobar....?api-version=zoomba',
    responses: {
      200: {
         headers: {. . .}
         body: { . . .}
       }
    }
}
```

**Comment by vladbarosan** [comment]
Closing this as stale
