### ISSUE TITLE
dependency on @microsoft.azure/autorest-extension-base to be updated.

### ISSUE THREAD

**Issue by amarzavery** [Azure/oav#208]
A package has been published for autorest-extension-base  as @microsoft.azure/autorest-extension-base -OAV is referencing that,. We should stop referencing it from github directly, and get it from npm. (and change any imports/require to "@microsoft.azure/autorest-extension-base"

**Comment by vladbarosan** [comment]
@amarzavery  yes I saw Johannes moved it to the Azure org at one point and asked him about and probably published the package also. I can update since I need to make another change probably.
