### ISSUE TITLE
comeup with a better mechanism to validate models for response codes in swagger

### ISSUE THREAD

**Issue by amarzavery** [Azure/oav#218]
- some operations have multiple response codes and we expect the spec author to provide example for all the response status codes.
- This makes sense for long running operations since we expect the spec author to describe the initial and final response status codes. Hence having an example for each of them in the same x-ms-example makes sense. This makes it easy for the doc team to show case sample responses in one snapshot on the doc site.
- There have been cases where people have documented the response code examples however they were not present in the swagger spec and we have helped them fix the issue early on in the process.

- We also need to come up with a mechanism to provide examples for negative responses (default) response code.

There are some services like media services where they have provided separate examples for create and update for operations like Assets_CreateOrUpdate and their assertion is that a particular response code will be given only in one of those scenarios (create or update). 

Hence we need to come up with a better mechanism to validate response status codes.

**Comment by a-hohaze** [comment]
@amarzavery is there an ETA for this?

**Comment by vladbarosan** [comment]
closing as stale.
