### ISSUE TITLE
Reaching out to partners for examples

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#22]

**Comment by salameer** [comment]
@kirthik, I worked on updating the onboarding documentation to request this from new teams onboarding to swaggers [here ](url) but I think we'll need to establish a formal process around requesting that. 

we have been able to extract examples from recording for different swaggers, @veronicagg can give you more updates on the status for those. but this will not be enough to cover all swaggers.

Sync-up with the Doc team on collaboration here would be critical

**Comment by amarzavery** [comment]
@salameer @kirthik @veronicagg - The purpose is pretty much achieved as most of the teams are ready to provide examples. Can we close this now?

**Comment by veronicagg** [comment]
Yes, closing.
