### ISSUE TITLE
Improve cache building performance

### ISSUE THREAD

**Issue by vladbarosan** [Azure/oav#230]
Right now for the whole azure rest specs it takes about 10 minutes to build the whole cache. We need to drastically reduce this to at least under 1 minute at least. 

It seems that we are doing a lot of nested for repeatedly while processing the specs. we could do just one and do the processing at the necessary level.

**Comment by amarzavery** [comment]
This was definitely there on the back of my mind.  I think we should move to building the cache asynchronously. Currently we are doing this synchronously. Processing one file after another.
Just doing the entire process  asynchronously would see a huge performance boost. Post that you can see if you need to dive deeper.

**Comment by vladbarosan** [comment]
Yea ill try to look after this, not sure if this sprint but next one.

**Comment by vladbarosan** [comment]
spread out in different tasks
