### ISSUE TITLE
Fix model validation issues for Search dataplane swagger spec

### ISSUE THREAD

**Issue by amarzavery** [Azure/oav#234]
- Please take a look at this PR https://github.com/Azure/azure-rest-api-specs/pull/2843.
- We need to do a better job at reporting errors.

It seems there is a bug in the regex validation for paths since path contains special characters like "(" and ")" which then causes the tool to incorrectly report path parameters that were provided in the example.

Another bug seems to be around validating polymorphic types. 

Please take a look at the CI job and also follow all the pain points pointed by Bruce Johnston in the PR conversation.

**Comment by mcardosos** [comment]
Did not find issues with polymorphism.
However found issues with `parametrized-host`. Open issue here https://github.com/Azure/oav/issues/240

**Comment by mcardosos** [comment]
Paths issue was fixed in https://github.com/Azure/oav/pull/238

**Comment by sarangan12** [comment]
Part 2 - Fixed
Part 3 - https://github.com/Azure/oav/issues/248 . needs to be fixed
