### ISSUE TITLE
x-ms-parametrized-host is not validated correctly

### ISSUE THREAD

**Issue by mcardosos** [Azure/oav#240]
Easy repro
`validate-example https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/search/data-plane/Microsoft.Azure.Search.Service/preview/2017-11-11/searchservice.json -o DataSources_Create`
Issue prolly needs to be fixed in sway

**Comment by amarzavery** [comment]
This should be fixed in the upcoming sprint. This will make sure that we can validate Azure search data plane swagger specs correctly. Please take a look at the referenced issue #234

**Comment by sarangan12** [comment]
Task completed and oav released
