### ISSUE TITLE
Move oav to typescript

### ISSUE THREAD

**Issue by vladbarosan** [Azure/oav#246]
we can do this step by step.

**Comment by amarzavery** [comment]
also consider using async/await wherever possible instead of promises. That will make the source code much cleaner.

**Comment by vladbarosan** [comment]
@amarzavery  yes ill tackle that part of the performance improvement issue #230  since probably will end up with some more async code there.

**Comment by vladbarosan** [comment]
We can close this as the effective transition has happened
