### ISSUE TITLE
Introduce different levels of results reporting

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#27]
Allow choosing verbose logging versus not, errors or all checks in output. Current output, with errors and then "swagger structured" output with passes and failures, is quite verbose and duplicated.

**Comment by amarzavery** [comment]
Have added support for logging. As of today the tool logs warning and above by default to console and everything from silly to error to a timestamp based log file

**Comment by amarzavery** [comment]
Feel free to close this one and open a new one with more specific actionable task item or add/modify this issue.
