### ISSUE TITLE
`$schema` references in examples don't have to be resolved

### ISSUE THREAD

**Issue by jianghaolu** [Azure/oav#271]
If an x-ms-example contains a `$schema` field in this response payload:

https://github.com/koralski/azure-rest-api-specs/blob/e3d9ca01eb41c555b03705a38e58173de2196194/specification/compute/resource-manager/Microsoft.Compute/stable/2018-04-01/examples/VirtualMachineRunCommandGet.json#L30

OAV will try to resolve the object from the link. This is not necessary in model validation.

**Comment by sergey-shandar** [comment]
Fixed.
