### ISSUE TITLE
Have a way to specify/handle "unusual" ARM operation urls

### ISSUE THREAD

**Issue by vladbarosan** [Azure/oav#283]
See https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2018-03-01/policyAssignments.json#L37

URL's coming now won't match to any operation ID

**Comment by vladbarosan** [comment]
@johanste any thoughts on this. scope parameter from the example doesn't have any restriction, theoretically it could match anything. Should we enforce to have a pattern here and then we could take that in consideration when trying to find the operation from the received url?

**Comment by johanste** [comment]
This problem surfaces for any path parameters that disable url encodings (something that Swagger/OpenAPI doesn't support natively btw.). 

I don't know exactly how our path matching logic is set up, but presumably, the path to the resource in this case uniquely identifies which RP the request should be routed to. Are we just extracting the first namespace to determine swagger today?

**Comment by raych1** [comment]
This is not a problem with {scope} defined in path and validation always uses the last RP as provider namespace.
