### ISSUE TITLE
Enable live testing of swagger documents, part 1

### ISSUE THREAD

**Issue by johanste** [Azure/oav#3]
- Authenticate
- Make request per request body response
- Validate that response code is one of the listed response codes in the example
- Validate that the response matches the schema for the response

**Comment by amarzavery** [comment]
Basic live testing support has been added.
Next item is to add support for adding a before and after in an example that provides deployment templates to create artifacts before running the example and destroy everything in the after section.

**Comment by vladbarosan** [comment]
closing this as stale and not relevant anymore.
