### ISSUE TITLE
For modelling implicit clouderror, if one is defined use that instead of the schema

### ISSUE THREAD

**Issue by vladbarosan** [Azure/oav#300]
`batchai/resource-manager/Microsoft.BatchAI/stable/2018-05-01/BatchAI.json` defines a `cloudError` and uses it except for some operations.

In this case, our current logic for modelling implicit default cloud error will assign "CloudErrorSchema" as a default response which wont exist. 

See the method here https://github.com/Azure/oav/blob/4fc35d48c67dbcbf13d9c9ee274301e1152714f2/lib/validators/specResolver.ts#L726

We should use the existing CloudError if it exists.

**Comment by sergey-shandar** [comment]
fixed
