### ISSUE TITLE
Error loading/parsing recording files with 0.5.8

### ISSUE THREAD

**Issue by sojain** [Azure/oav#309]
```
{ message: 'Errors loading/parsing recording files.',
  level: '\u001b[31merror\u001b[39m',
  [Symbol(level)]: 'error',
  [Symbol(message)]: '{"message":"Errors loading/parsing recording files.","level":"error"}' }
{ message: '{"E:\\\\work\\\\git\\\\azure-sdk-for-net\\\\src\\\\SDKs\\\\DataBox\\\\DataBox.Tests\\\\SessionRecords\\\\DataBox.Tests.Tests.JobCRUDTests\\\\TestJobCRUDOperations.json":"TypeError: entries(...) is not a function or its return value is not iterable",
```

[TestJobCRUDOperations.txt](https://github.com/Azure/oav/files/2371145/TestJobCRUDOperations.txt)

Can someone please help with the same

**Comment by sergey-shandar** [comment]
@sojain could you provide more context?
- what do you run? OAV/AutoRest/etc.
- where do you run? CI/local/VSCode/etc.
- and why?

**Comment by sojain** [comment]
Command run
oav extract-xmsexamples "E:\work\git\azure-rest-api-specs\azure-rest-api-specs\specification\databox\resource-manager\Microsoft.DataBox\preview\2018-01-01\databox.json" "E:\work\git\azure-sdk-for-net\src\SDKs\DataBox\DataBox.Tests\SessionRecords"

I had run it in cmd in admin mode, this is to generate examples and validate my swagger spec

**Comment by sergey-shandar** [comment]
@sojain please try 0.5.10
