### ISSUE TITLE
OAV API shouldn't throw exceptions for invalid json (or known errors)

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/oav#313]
Currently, there are a lot of exported functions in OAV that throw exceptions. OAV functions should either
- return union `Result|Error`
- use callback function (dependency injection) `reportError: (e: Error) => void`.

**Comment by raych1** [comment]
This issue was fixed and below error will be reported in case of invalid JSON.
RESOLVE_SPEC_ERROR: unexpected token, token: :, line: 32, column: 12
