### ISSUE TITLE
Validating example that retrieve polymorphic type

### ISSUE THREAD

**Issue by anuchandy** [Azure/oav#349]
When oav validates the example [getAMLCompute](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/examples/getAMLCompute.json)

it shows [this](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/450058400#L614) error 

which says example should not have following properties:

```
          - nodeStateCounts
          - targetNodeCount
          - currentNodeCount
          - scaleSettings
          - subnet
          - vmPriority
          - vmSize
          - errors
          - allocationStateTransitionTime
          - allocationState
```

The model defined as response type for `MachineLearningCompute_Get`  is               [ComputeResource](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json#L563).

ComputeResource [composes](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json#L1332) the model [Compute](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json#L1338), which has discriminator property as [computeType](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json#L1341).

AMLCompute [inherits](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json#L1451) from Compute model with discriminator property value as [AMLCompute](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json#L1540). AMLCompute model has all the above properties reported as missing in oav report.

**Comment by anuchandy** [comment]
Similar error on validating the example [JobGet2](https://github.com/Azure/azure-rest-api-specs/blob/3f738b23f785efc0f3e35452b44b8328a1aabbe0/specification/databox/resource-manager/Microsoft.DataBox/stable/2018-01-01/examples/JobsGet2.json)

It shows [this]() error 

which says example should not have the following property:

```
copyProgress
```

The model defined as response type for `Jobs_Get` is [JobResource](https://github.com/Azure/azure-rest-api-specs/blob/3f738b23f785efc0f3e35452b44b8328a1aabbe0/specification/databox/resource-manager/Microsoft.DataBox/stable/2018-01-01/databox.json#L1709).

JobResource [composes](https://github.com/Azure/azure-rest-api-specs/blob/3f738b23f785efc0f3e35452b44b8328a1aabbe0/specification/databox/resource-manager/Microsoft.DataBox/stable/2018-01-01/databox.json#L1722) the model `JobProperties`, which [composes](https://github.com/Azure/azure-rest-api-specs/blob/3f738b23f785efc0f3e35452b44b8328a1aabbe0/specification/databox/resource-manager/Microsoft.DataBox/stable/2018-01-01/databox.json#L1699) JobDetails. JobDetails has discriminator property as [JobDetailsType](https://github.com/Azure/azure-rest-api-specs/blob/3f738b23f785efc0f3e35452b44b8328a1aabbe0/specification/databox/resource-manager/Microsoft.DataBox/stable/2018-01-01/databox.json#L1561).

[DataBoxJobDetails](https://github.com/Azure/azure-rest-api-specs/blob/3f738b23f785efc0f3e35452b44b8328a1aabbe0/specification/databox/resource-manager/Microsoft.DataBox/stable/2018-01-01/databox.json#L1239) inherits from JobDetails and had discriminator property value as [DataBox](https://github.com/Azure/azure-rest-api-specs/blob/3f738b23f785efc0f3e35452b44b8328a1aabbe0/specification/databox/resource-manager/Microsoft.DataBox/stable/2018-01-01/databox.json#L1263). DataBoxJobDetails has the copyProgress property reported as missing in oav report.

**Comment by msoni3** [comment]
> 
> 
> When oav validates the example [getAMLCompute](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/examples/getAMLCompute.json)
> 
> it shows [this](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/450058400#L614) error
> 
> which says example should not have following properties:
> 
> ```
>           - nodeStateCounts
>           - targetNodeCount
>           - currentNodeCount
>           - scaleSettings
>           - subnet
>           - vmPriority
>           - vmSize
>           - errors
>           - allocationStateTransitionTime
>           - allocationState
> ```
> 
> The model defined as response type for `MachineLearningCompute_Get` is [ComputeResource](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json#L563).
> 
> ComputeResource [composes](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json#L1332) the model [Compute](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json#L1338), which has discriminator property as [computeType](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json#L1341).
> 
> AMLCompute [inherits](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json#L1451) from Compute model with discriminator property value as [AMLCompute](https://github.com/Azure/azure-rest-api-specs/blob/41f80143a85d16c0ddaa642a3d92d444dd7cda28/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json#L1540). AMLCompute model has all the above properties reported as missing in oav report.

This is now fixed.
