### ISSUE TITLE
UNRESOLVABLE_REFERENCE for URLs with trailing '#' character

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/oav#373]
Complete build log https://travis-ci.org/Azure/azure-rest-api-specs/jobs/477980402, here's a sample.

```
 error : 
operationId: Workflows_ListBySubscription
scenario: List all workflows in a subscription
source: request
responseCode: ALL
severity: 0
errorCode: UNRESOLVABLE_REFERENCE
errorDetails:
  code: UNRESOLVABLE_REFERENCE
  params:
    - >-
      https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#
  message: >-
    Reference could not be resolved:
    https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#
  path: >-
```

**Comment by sergey-shandar** [comment]
@jhendrixMSFT It looks like OAV is trying to resolve `$schema` in examples https://github.com/Azure/azure-rest-api-specs/blob/master/specification/logic/resource-manager/Microsoft.Logic/preview/2018-07-01-preview/examples/Workflows_CreateOrUpdate.json#L15 .

As a simple workaround, the `$schema` property can be removed from examples.

**Comment by jhendrixMSFT** [comment]
I mentioned that to the swagger owner, they were hesitant to do so given that the service returns this in their response.  What is supposed to be resolved with the trailing '#'?

**Comment by sergey-shandar** [comment]
@jhendrixMSFT I believe OAV shouldn't resolve reference/$schemas etc. in example files. It's a bug.

**Comment by sergey-shandar** [comment]
Duplicate #271

**Comment by jhendrixMSFT** [comment]
Closing since it's a dupe, hopefully 271 will get fixed soon :).
