### ISSUE TITLE
ARM resource_group should always be called ResourceGroupName

### ISSUE THREAD

**Issue by lmazuel** [Azure/oav#392]
There should be a rule, to enforce anything called "resourcegroup" to follow this:
https://github.com/Azure/azure-rest-api-specs/blob/46dd1d23b20e3a85eb1422f2c8c5fc1223b296f5/specification/common-types/resource-management/v1/types.json#L290-L300

(if it's not the right repo please move it :))

**Comment by mozehgir** [comment]
@vladbarosan please move to https://github.com/Azure/azure-openapi-validator
