### ISSUE TITLE
OAV model validation throws ICE: value.code is undefined

### ISSUE THREAD

**Issue by vladbarosan** [Azure/oav#397]
For repro execute example validation against https://raw.githubusercontent.com/billytrend/azure-rest-api-specs/dev-cdn-Microsoft.Cdn-6/specification/cdn/resource-manager/Microsoft.Cdn/preview/6/cdn.json

The example that fails: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cdn/resource-manager/Microsoft.Cdn/stable/2017-10-12/examples/CustomDomains_EnableCustomHttpsUsingBYOC.json

The error that does not have a code is : `"Invalid parameter (customDomainHttpsParameters): Cannot read property 'readUInt8' of null"`

looking at the spec and example 2 things are showing up:
- the name in the spec for the param is: `customDomainHttpsParameters`  while in the example is `customHttpsParameters`
- the schema for it is polymorphic

**Comment by vladbarosan** [comment]
please @sergey-shandar  if you can have a look

**Comment by amarzavery** [comment]
I looked at this issue. It has nothing to do with oav. The examples are incorrect.
There are some errors in both the examples provided for operation  CustomDomains_EnableCustomHttps in the file specification/cdn/resource-manager/Microsoft.Cdn/preview/2019-06-15-preview/cdn.json

The name of body parameter in the example and the spec does not match.
The name of the property in CdnCertificateSourceParameters and KeyVaultCertificateSourceParameters in the spec is "@odata.type" and in the examples is "OData.type". Hence either the example is correct or the swagger spec. Please change one f them based on what is happening in the wire

https://github.com/Azure/azure-rest-api-specs/pull/5885

**Comment by raych1** [comment]
There're two PRs in yasway and ms-rest packages
Azure/sway#80 and Azure/azure-sdk-for-node#5090 to fix this issue.

**Comment by vladbarosan** [comment]
@raych1  after merging this, please make sure to close the task please

**Comment by raych1** [comment]
Close this issue since the fix was merged.
