### ISSUE TITLE
Model validation says it succeeds but there are errros 

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#407]
Job https://travis-ci.org/Azure/azure-rest-api-specs/jobs/513289559 
https://github.com/Azure/azure-rest-api-specs/pull/5475/checks?check_run_id=88610936

PR https://github.com/Azure/azure-rest-api-specs/pull/5475

@sergey-shandar

**Comment by veronicagg** [comment]
Another example: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/515366892#L535
Could we prioritize this? I'm pretty sure it's letting model validation errors in the azure-rest-api-specs repo.

**Comment by sergey-shandar** [comment]
Fixed in azure-rest-api-specs.
