### ISSUE TITLE
Consider erroring on missing `host` element

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/oav#413]
In reference to https://github.com/Azure/azure-rest-api-specs/pull/5580

Per OpenAPI spec the `host` element is optional however I believe that all of our code generators rely on it when creating clients.  See also https://github.com/Azure/azure-sdk-for-go/issues/4486 for how this affected the Go SDK.

**Comment by mozehgir** [comment]
@vladbarosan please add as linter rule https://github.com/Azure/azure-openapi-validator
