### ISSUE TITLE
Fix INTERNAL_ERROR

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/oav#417]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=18037

**Comment by kpajdzik** [comment]
Example PR: https://github.com/Azure/azure-rest-api-specs/pull/5893

**Comment by veronicagg** [comment]
I'm also seeing it as an error when running model validation for specification/cdn/resource-manager/Microsoft.Cdn/stable/2019-04-15/cdn.json
INTERNAL ERROR on Operation Id CustomDomains_EnableCustomHttps on request for- Scenarios: CustomDomains_EnableCustomHttpsUsingYourOwnCertificate and CustomDomains_EnableCustomHttpsUsingCDNManagedCertificate

**Comment by raych1** [comment]
There're two PRs in yasway and ms-rest packages  
https://github.com/Azure/sway/pull/80 and https://github.com/Azure/azure-sdk-for-node/pull/5090 to fix this issue.

**Comment by raych1** [comment]
This issue was fixed.
