### ISSUE TITLE
Updating & Standardizing the top level summary of the JSON output of this tool

### ISSUE THREAD

**Issue by salameer** [Azure/oav#42]
in our efforts to standardize the output of our validation tools to:
- Make it more human readable
- Make it easier and more performant for potential visualizers to process and also categorize the output according to the tools that were used to process it.
- Provide useful versioning & performance information

I'm suggesting that we start with standardizing the top level summary of the JSON output of this tool, as follows

```javascript
{
  json_file: 'C:\Users\sameal\Documents\GitHub\openapi-validation-tools\arm-mediaservices\2015-10-01\swagger\media.json',
  validationTool: 'model_validator',
  validationToolVersion: '0.1.0',
  validationCommand: 'example',
  validationSummary: {
    validityStatus: false,
    numOfOperationsInFile: '50',
    numOfFailedOperations: '23',
    validationTime: '550'
  },
  validation_result: {
    operations: {
      MediaService_CheckNameAvailability: {
        'example-in-spec': {
          parameters: {
            CheckNameAvailabilityInput: {
              isValid: true,
              result: 'The example for body parameter CheckNameAvailabilityInput with reference #/definitions/CheckNameAvailabilityInput in operation "MediaService_CheckNameAvailability" is valid.'
            }
          },
          responses: {
            '200': {
              isValid: true,
              result: 'The example for response with statusCode "200" in operation "MediaService_CheckNameAvailability" is valid.'
            }
          }
        }
      }
    }
  }
}
```

**Comment by salameer** [comment]
Validate with Johan the metrics that he'd like to capture before designing the summary JSON

**Comment by salameer** [comment]
@johanste

**Comment by salameer** [comment]
The description of this task is more of an example, add what ever parameters that are required to capture the required metrics

**Comment by salameer** [comment]
@veronicagg we synced with @fearthecowboy regarding standardizing the output across all of our tools kindly sync up with him on the format required.

**Comment by vladbarosan** [comment]
Closing this as stale
