### ISSUE TITLE
OAV doesnt proper validate nested discriminated types with an a property called "allOf"

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/oav#421]
The following PR gave validator error
https://github.com/Azure/azure-rest-api-specs/pull/5677/

Model validator log
https://dev.azure.com/azure-sdk/public/_build/results?buildId=19420

operationId: MetricAlerts_Get
scenario: Get an alert rule on resource group(s)
source: response
responseCode: '200'
severity: 0
code: ENUM_MISMATCH
details:
  code: ENUM_MISMATCH
  params:
    - StaticThresholdCriterion
  message: 'No enum match for: StaticThresholdCriterion'
  path: properties/criteria/allOf/0/criterionType
  title: '#/definitions/MultiMetricCriteria/properties/criterionType'
  position:
    line: 638
    column: 27
  url: >-
    specification/monitor/resource-manager/Microsoft.Insights/stable/2018-03-01/metricAlert_API.json
  directives:
    R3016: .*
  jsonUrl: >-
    specification/monitor/resource-manager/Microsoft.Insights/stable/2018-03-01/examples/getMetricAlertResourceGroup.json

**Comment by vladbarosan** [comment]
underlying issue is that there is a property called allOf in the nested discriminated types which seems to not be processed properly.

**Comment by raych1** [comment]
This issue was fixed.
