### ISSUE TITLE
OAV not reporting example position for INVALID_TYPE error in request

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#423]
https://github.com/Azure/azure-rest-api-specs/blob/f9f5d84cf22d860a02fb3188a58863c4241a89b6/specification/adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService/stable/2014-01-01/ADHybridHealthService.json

Output contains an INVALID_TYPE error in the REQUEST and points to the spec but not the corresponding position in the example 
Details:
Show inner error
Details: "Expected type object but found type array"
Spec location: specification/adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService/stable/2014-01-01/ADHybridHealthService.json#L6213

Operation ID - addsServices_update
Scenario = addsServices_update
Source= request
ErrorCode INVALID_TYPE

**Comment by raych1** [comment]
@veronicagg here're the detail error message. It's clear to see the complained parameter name is 'service' though it doesn't have the line number of the example file. I would say won't fix. 
@amarzavery @sergey-shandar , do you have any comment on this issue? 
```
 code: 'REQUEST_VALIDATION_ERROR',
  id: 'OAV109',
  message:
   'Found errors in validating the request for x-ms-example "addsServices_update" in operation "addsServices_update".:\nFound errors in validating the request for x-ms-example "addsServices_update" in operation "addsServices_update".',
  innerErrors:
   [ { code: 'INVALID_REQUEST_PARAMETER',
       errors:
        [ { code: 'INVALID_TYPE',
            params: [ 'object', 'array' ],
            message: 'Expected type object but found type array',
            path: [],
            title:
             '{"path":["definitions","ServiceProperties"],"position":{"line":6213,"column":26},"url":"D:/git/github/azure-rest-api-specs/specification/adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService/stable/2014-01-01/ADHybridHealthService.json","directives":{}}',
            description: 'The service properties for a given service.' } ],
       in: 'body',
       message:
        'Invalid parameter (service): Value failed JSON Schema validation',
       name: 'service',
       schemaPath:
        '#/paths/~1providers~1Microsoft.ADHybridHealthService~1addsservices~1{serviceName}/patch/parameters/1' } ],
  level: '\u001b[31merror\u001b[39m' }
```

**Comment by sergey-shandar** [comment]
@raych1 this is one is important because it's hard for users to see where is the problem. Also OpenAPI Hub will not show a link to example error as well @vladbarosan @billytrend.

**Comment by vladbarosan** [comment]
@sergey-shandar , @raych1  correct, the hub wont be able to show a link without the source locaiton

**Comment by raych1** [comment]
Closed as the fix was merged.
