### ISSUE TITLE
OAV should resolve `allOf` before validating.

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/oav#431]
`allOf` shouldn't be used as it used in [JSON-Schema](https://json-schema.org/understanding-json-schema/reference/combining.html#allof). AutoRest combines definition into one and most of our customers assumes that this is correct behavior. For example

This OpenAPI 2.0 definition
```json
{
  "allOf": [ 
    { "properties": { "a": { "type": "string" } } },
    { "properties": { "b": { "type": "string" } } }
  ]
}
```
should report an error on
```
{ "a": "Hello", "b": "world!" }
``` 
but AutoRest assumes that this should pass and be equal to
```json
{
  "properties": { "a": { "type": "string" }, "b": { "type": "string" } }
}
```

**Comment by sergey-shandar** [comment]
@shahabhijeet @amarzavery

**Comment by raych1** [comment]
Investigation result: this is not real OAV issue. OAV can resolve "AllOf" correctly before validating. The associated PR has mismatching issue between example and the swagger spec.
