### ISSUE TITLE
Internal error validating machineLearningServices.json

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/oav#433]
Please see https://github.com/Azure/azure-rest-api-specs/pull/6432 for the repro.

TypeError: An Internal Error occurred in validating the spec "specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2019-06-01/machineLearningServices.json". 	Cannot read property 'path' of undefined.

  | at ZSchema.readOnlyValidator (/home/vsts/work/1/s/node_modules/yasway/lib/validation/custom-zschema-validators.js:223:28) |  
  | at ZSchema.exports.validate (/home/vsts/work/1/s/node_modules/z-schema/src/JsonValidation.js:594:39) |  
  | at ZSchema.validate (/home/vsts/work/1/s/node_modules/z-schema/src/ZSchema.js:242:33) |  
  | at Object.module.exports.validateAgainstSchema (/home/vsts/work/1/s/node_modules/yasway/lib/helpers.js:481:25) |  
  | at validateDefaultValue (/home/vsts/work/1/s/node_modules/yasway/lib/validation/validators.js:200:22) |  
  | at /home/vsts/work/1/s/node_modules/yasway/lib/validation/validators.js:97:5 |  
  | at arrayEach (/home/vsts/work/1/s/node_modules/lodash/lodash.js:516:11) |  
  | at Function.forEach (/home/vsts/work/1/s/node_modules/lodash/lodash.js:9344:14) |  
  | at walkSchema (/home/vsts/work/1/s/node_modules/yasway/lib/validation/validators.js:96:5) |  
  | at /home/vsts/work/1/s/node_modules/yasway/lib/validation/validators.js:72:7 |  
  | code: 'INTERNAL_ERROR', |  
  | id: 'OAV100', |  
  | level: 'error', |  
  | [Symbol(level)]: 'error', |  
  | [Symbol(message)]: '{"code":"INTERNAL_ERROR","id":"OAV100","level":"error"}'

**Comment by sergey-shandar** [comment]
The issue has been fixed. CI was re-run and the validation passed.
