### ISSUE TITLE
Create Centralized documentation for all of our Swagger validation tools

### ISSUE THREAD

**Issue by salameer** [Azure/oav#44]
The idea of this documentation is to point the Swagger author to all the swagger validation tools that he can use while authoring his swaggers, and provide:

- Clear and simple instructions to install the tools
- Clearly and simple description of how to execute the tool (with complete example commands if applicable)
- Clearly and simple examples of what type of issues would each tool catch. 
- At which step in the process of creating the swagger should every tool be used.

We can document this in the Wiki of this tool or create a documentation folder. This will also help us in our future integration with VS Code.

**Comment by salameer** [comment]
@kirthik you can use this task to track the documentation efforts of our tools. the documentation can definitely be referenced from the Swagger checklist and eventually shared with the customers.

**Comment by veronicagg** [comment]
@salameer is this issue still valid?
