### ISSUE TITLE
extract-xmsexamples documentation is not very specific 

### ISSUE THREAD

**Issue by estebanreyl** [Azure/oav#441]
This is probably not a big issue nor something most experienced .NET developer will run into but I've been trying to use the extract-xmsexamples command to generate example files for my team's swagger (Azure Container Registries) and I cannot seem to figure out what the second parameter refers to <recordings> . I have setup a .Net project in which I am using our Autorest generated C sharp sdk  nonetheless I have no clue what .NET session recordings refer to nor can find any documentation online for this term.  Is it possible to add at least a link providing clarification for this in the readme.md/did I miss something?

Example:
```bash
bash-3.2$ oav -h
Commands:
  extract-xmsexamples <spec-path>           Extracts the x-ms-examples for a
  <recordings>                              given swagger from the  .NET session
                                            recordings and saves them in a file.
```
For more information on .NET session recordings see [here](http://docsonthis.com)

**Comment by raych1** [comment]
@estebanreyl, here're some [sample files](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Microsoft.Azure.Management.Storage/tests/SessionRecords/Storage.Tests.StorageAccountTests/StorageAccountFailOver.json) of .NET session recordings. I am looking for the guideline to generate the recordings.

**Comment by estebanreyl** [comment]
@raych1 Thanks for replying! In the end I handcrafted the example files but I think this is something that needs to be clarified for future users. A guideline as you mentioned would be very helpful.

**Comment by raych1** [comment]
@estebanreyl, here is the [document](https://github.com/Azure/azure-sdk-for-net/blob/master/Documentation/Using-Azure-TestFramework.md) to create the .NET test recordings.
I close this issue and feel free to reactivate it in case of any questions.
