### ISSUE TITLE
Provide clearer message for spec validation error in definition

### ISSUE THREAD

**Issue by lirenhe** [Azure/oav#453]
"definitions": {
    "Resource": {
      "description": "An Azure resource.",
      "properties": {
        "id": {
          "description": "Azure resource Id.",
          "type": "string",
          "readOnly": true
        },

        },
        "x-ms-azure-resource": true
      }
    }
}

For the incorrect place of line 'x-ms-azure-resource', we need to report a clearer error message instead of 'model cannot be null or undefined and must of type "object"..'  which is very difficult to trouble shooting.

**Comment by raych1** [comment]
The error is like:
``` code 
...internal error: model cannot be null or undefined and must of type "object"...
```
All the properties are supposed to be object and DONOT allow primitive type.
Fix to improve the message: maybe around the [here](https://github.com/Azure/oav/blob/6bf90059b9e9ba59bc0759cc8fdeac7c92b3b49d/lib/validators/resolveNestedDefinitions.ts#L80).

**Comment by raych1** [comment]
This issue was fixed.
