### ISSUE TITLE
API version and resource provider name should be case-insensitive for live validation

### ISSUE THREAD

**Issue by lirenhe** [Azure/oav#460]
we need to follow ARM to detect the API version and the resource provider name.

**Comment by nickzhums** [comment]
After inspecting the code, I found the following.

During Cache Initialization
Both provider and api version will be converted to lower case when cache is being built
`async getSwaggerInitializer(swaggerPath) {
        const startTime = Date.now();
        this.logging(`Building cache from: "${swaggerPath}"`, LiveValidatorLoggingLevels.debug);
        const validator = new specValidator_1.SpecValidator(swaggerPath, null, {
            isPathCaseSensitive: this.options.isPathCaseSensitive,
            shouldResolveXmsExamples: false
        });
        try {
            const startTimeLoadSpec = Date.now();
            const api = await validator.initialize();
            const elapsedTimeLoadSpec = Date.now() - startTimeLoadSpec;
            this.logging(`Load spec for ${swaggerPath} with DurationInMs:${elapsedTimeLoadSpec}`, LiveValidatorLoggingLevels.debug, "Oav.liveValidator.getSwaggerInitializer.specValidator.initialize");
            const operations = api.getOperations();
            let apiVersion = api.info.version.toLowerCase();
            for (const operation of operations) {
                const httpMethod = operation.method.toLowerCase();
                const pathObject = operation.pathObject;
                const pathStr = pathObject.path;
                let provider = utils.getProvider(pathStr);
                this.logging(`${apiVersion}, ${operation.operationId}, ${pathStr}, ${httpMethod}`, LiveValidatorLoggingLevels.debug);
                if (!provider) {
                    const title = api.info.title;
                    // Whitelist lookups: Look up knownTitleToResourceProviders
                    // Putting the provider namespace onto operation for future use
                    if (title && C.knownTitleToResourceProviders[title]) {
                        operation.provider = C.knownTitleToResourceProviders[title];
                    }
                    // Put the operation into 'Microsoft.Unknown' RPs
                    provider = C.unknownResourceProvider;
                    apiVersion = C.unknownApiVersion;
                    this.logging(`Unable to find provider for path : "${pathObject.path}". ` +
                        `Bucketizing into provider: "${provider}"`, LiveValidatorLoggingLevels.debug);
                }
                provider = provider.toLowerCase();
                // Get all api-version for given provider or initialize it
                const apiVersions = this.cache[provider] || {};
                // Get methods for given apiVersion or initialize it
                const allMethods = apiVersions[apiVersion] || {};
                // Get specific http methods array for given verb or initialize it
                const operationsForHttpMethod = allMethods[httpMethod] || [];
                // Builds the cache
                operationsForHttpMethod.push(operation);
                allMethods[httpMethod] = operationsForHttpMethod;
                apiVersions[apiVersion] = allMethods;
                this.cache[provider] = apiVersions;
            }
            const elapsedTime = Date.now() - startTime;
            this.logging(`DurationInMs:${elapsedTime}`, LiveValidatorLoggingLevels.debug, "Oav.liveValidator.getSwaggerInitializer");
        }
        catch (err) {
            // Do Not reject promise in case, we cannot initialize one of the swagger
            this.logging(`Unable to initialize "${swaggerPath}" file from SpecValidator. Error: ${err}`, LiveValidatorLoggingLevels.debug);
            this.logging(`Unable to initialize "${swaggerPath}" file from SpecValidator. We are ` +
                `ignoring this swagger file and continuing to build cache for other valid specs.`, LiveValidatorLoggingLevels.warn);
        }
    }`

During validating, provider is already being converted to lowercase, however api-version IS NOT. This causes problems if api-version is like '2018-01-01-STABLE / stable '
`      apiVersion = queryObject["api-version"] as string
      providerNamespace = utils.getProvider(pathStr) || C.unknownResourceProvider
      resourceType = utils.getResourceType(pathStr, providerNamespace)

      // Provider would be provider found from the path or Microsoft.Unknown
      providerNamespace = providerNamespace || C.unknownResourceProvider
      if (providerNamespace === C.unknownResourceProvider) {
        apiVersion = C.unknownApiVersion
      }
      providerNamespace = providerNamespace.toLowerCase()
      queryStr = parsedUrl.query
      requestMethod = requestMethod.toLowerCase()`

Therefore changes need to be made for 

1. During validation, api-version needs to be converted to lower case, provider can be left unchanged
2. Add unit tests

**Comment by raych1** [comment]
This issue was fixed.
