### ISSUE TITLE
Support for exclusion of reported issues in tool

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#57]
We may need to suppress certain errors or warnings from result of the tool.

**Comment by salameer** [comment]
@amarzavery  and @veronicagg are we thinking around the same lines of supper-sing rules for the linter? are we going to depend on stuff authored into the swagger to suppress these warning or is this a simple  removal of all the noise?

**Comment by veronicagg** [comment]
for the options that get hooked up to autorest, we can use suppression mechanism from autorest to not report the issues for azure-rest-api-specs.
