### ISSUE TITLE
failed to validate enum value for discriminator field

### ISSUE THREAD

**Issue by leni-msft** [Azure/oav#581]
https://github.com/leni-msft/azure-rest-api-specs-pr/blob/69746cf2084673eb3d2994e130c87930910b74ed/specification/hardwaresecuritymodules/resource-manager/Microsoft.HardwareSecurityModules/preview/2018-10-31-preview/examples/DedicatedHsm_CreateOrUpdate.json#L23

**Comment by raych1** [comment]
This was fixed in new version of model validation.
