### ISSUE TITLE
OAV 2.8.0 JSON Parsing Error

### ISSUE THREAD

**Issue by molson194** [Azure/oav#659]
After updating to OAV 2.8.0, I'm getting the following error

`code: JSON_PARSING_ERROR
message: 'Json parsing error: invalid symbol'
position:
  line: 1
  column: 1
url: >-
  <SRC_PATH>\Swagger\2021-05-01-preview\examples\OperationsGet.json`

Here is my json file (I can't see an invalid symbol)

`{
    "parameters": {
        "api-version": "2021-05-01-preview"
    },
    "responses": {
        "200": {
            "body": []
        }
    }
}`

**Comment by ruowan** [comment]
sorry for delay response. It maybe due to your file encoding. Pls make sure your json file encode is utf-8 without bom.

**Comment by raych1** [comment]
Yes, I already synced up with @molson194 offline and close on this issue.
