### ISSUE TITLE
validateLiveRequest failed for format=="base64url"

### ISSUE THREAD

**Issue by changlong-liu** [Azure/oav#697]
For option using schema here: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2021-06-01-preview/keys.json#L636,
the validateLiveRequest failed with below message:
![image](https://user-images.githubusercontent.com/59815250/139783080-d7545cc7-eca5-4300-ae1c-600463864522.png)

**Comment by raych1** [comment]
It needs to add support on this customized format.

**Comment by raych1** [comment]
Fixed in oav@2.10.2
