### ISSUE TITLE
Report on coverage for swagger document examples

### ISSUE THREAD

**Issue by johanste** [Azure/oav#7]
Consider both paths hit as well as permutations for complex model types (i.e. for collection properties, have you tried 0, 1, n items in the collection etc.)

**Comment by salameer** [comment]
@johanste, let's clean this up a bit here. 

We need to start somewhere with our coverage reporting and for milestone 1:

- Traversing all of our swaggers and calculating the percentage of x-ms-examples in all of the swaggers.
- .Net SDK tests coverage for a swagger file

We're looking to build tools that will helps us push toward the "Preview Vs Stable" swaggers proposal

@johanste & @ravbhatnagar

**Comment by veronicagg** [comment]
@sergey-shandar FYI

**Comment by vladbarosan** [comment]
closing this as stale.
