### ISSUE TITLE
bug: oav wrong live validation for the array query param

### ISSUE THREAD

**Issue by tadelesh** [Azure/oav#756]
rp: applicationinsights
operation: Workbooks_ListBySubscription
problem: `tags` is an array query param for the list operation. When giving empty query string like `tags=` or meaningful query string like `tags=a,b,c`, oav live validation will give a false alarm of `INVALID_TYPE` with message `Expected type array but found type string`.
oav version: 2.10.2

**Comment by daniel-rocha** [comment]
This validation caused quite a few problems for Azure Maps as well @raych1 and @keryul. I will get in touch with you offline to discuss.

**Comment by raych1** [comment]
This was resolved in code.
