### ISSUE TITLE
Support new format `arm-id` and associated extension `x-ms-arm-id-details`

### ISSUE THREAD

**Issue by matthchr** [Azure/oav#765]
This annotation was [proposed and accepted](https://github.com/Azure/autorest/pull/4150) recently.

I then attempted to use it in [various service Swaggers](https://github.com/Azure/azure-rest-api-specs/pull/18318) but realized that it is causing the model/semantic validator to fail.

Would it be possible to add support for this format and annotation? The model validator should also probably use this to check that the provided sample gives a resource ID that matches.

Filing this at the mention of @leni-msft.

**Comment by leniatgh** [comment]
@raych1 pls help check

**Comment by matthchr** [comment]
Any update on this? Let me know if there's anything I can do to help progress this.

**Comment by raych1** [comment]
@matthchr , this is new extension to support. I think the support on this can be divided into two phases, the first phase is to recognize this new schema and don't report error on schema; the second phase is to add validation on arm-id value.
