### ISSUE TITLE
Generated examples use non-standard example domain

### ISSUE THREAD

**Issue by abatishchev** [Azure/oav#791]
Currently they're generating this:

```json
{
"headers": {
    "Azure-AsyncOperation": "https://foo.com/operationstatus"
  }
}
```

However there are better options:

- [RFC 2606](https://datatracker.ietf.org/doc/html/rfc2606) suggests to use `example.com`
- [Microsoft REST API Guideline](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md)  uses `contoso.com`
- Use `management.azure.com`, always or figure it out based on some input or somehow else

**Comment by raych1** [comment]
This request is resolved in oav@3.0.1
