### ISSUE TITLE
Generated examples don't include title nor operation id

### ISSUE THREAD

**Issue by abatishchev** [Azure/oav#793]
Both fields must be present in order for Cadl to work.

See https://github.com/Azure/cadl-azure/blob/c65790e6181ecca8ac25e99b5b378cc1e9ddda59/packages/cadl-autorest/src/openapi.ts#L757

**Comment by abatishchev** [comment]
@raych1 hi Ray, do you know if this can be prioritized so oav-generated examples would work fine with Cadl?

**Comment by raych1** [comment]
@abatishchev , how about using the description of operation as the title of example?

**Comment by abatishchev** [comment]
@raych1 here's what I currently put:

```json
{
  "operationId": "<file name>",
  "title": "<file name>",
}
```

But putting something more meaningful is better!

**Comment by abatishchev** [comment]
Here's the line in Cadl that checks for the presence of both:

https://github.com/Azure/cadl-azure/blob/84c78a802d3fc8c96d049335123cfe5102177a77/packages/cadl-autorest/src/openapi.ts#L998-L1006

But I don't know how it's used down the stream.

**Comment by raych1** [comment]
@abatishchev , these two properties are added to the generated examples in version 3.2.1 and will be released soon.
