### ISSUE TITLE
Support validating duration format

### ISSUE THREAD

**Issue by leniatgh** [Azure/oav#811]
The value `"disconnectDelay": "00:05",` is not valid `duration` format, defined here: https://github.com/Azure/azure-rest-api-specs/pull/16557/files#diff-3c4db78d53e5371a8535d5e3605c358012d88939dacc237a6a8441b4bbed68caR257

`duration` is new format added in Draft 2019-09, since we allow specifying in swagger, we should validate the example value as well.

**Comment by raych1** [comment]
@keryul , I remember this is supported. Can you check?

**Comment by raych1** [comment]
This format is supported in oav@3.0.1
