### ISSUE TITLE
npm audit reports oav versions later than 0.18.3 have dependency on package with vulnerability (yuml2svg, depends on jsdom)

### ISSUE THREAD

**Issue by laurawalker** [Azure/oav#852]
npm audit output:

npm audit report

jsdom  <=16.4.0
Severity: moderate
Insufficient Granularity of Access Control in JSDom - https://github.com/advisories/GHSA-f4c9-cqv8-9v98
fix available via `npm audit fix --force`
Will install oav@0.18.2, which is a breaking change
node_modules/oav/node_modules/jsdom
  yuml2svg  4.0.0-0 - 5.0.0-rc.1
  Depends on vulnerable versions of jsdom
  node_modules/oav/node_modules/yuml2svg
    oav  >=0.18.3
    Depends on vulnerable versions of yuml2svg
    node_modules/oav

**Comment by raych1** [comment]
The change will be released this week.

**Comment by raych1** [comment]
The fix was released at oav@3.2.0
