### ISSUE TITLE
Support x-nullable

### ISSUE THREAD

**Issue by vishrutshah** [Azure/oav#86]
need to understand how does Autorest process, x-nullable in different scenarios:
- what is the default behavior?
- type of the property or the parameter (string, number, Array, complex type, dictionary, enum)
- what if the property or the parameter is required

**Comment by veronicagg** [comment]
related https://github.com/Azure/azure-rest-api-specs/issues/798

**Comment by amarzavery** [comment]
related #116

**Comment by amarzavery** [comment]
This PR https://github.com/Azure/oav/pull/185 adds support for x-nullable for model validation in oav.
