### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by vw52** [Azure/oav#866]
I am seeing an oav error message that i don't know how to debug:

 unacceptable kind of an object to dump [object Error] https://github.com/Azure/azure-rest-api-specs-pr/pull/8670/checks?check_run_id=8333101401
![image](https://user-images.githubusercontent.com/1521816/189967313-72db4efa-5b47-4fd1-8e2e-9b0420a4cb0f.png)

}
/mnt/vss/_work/1/azure-rest-api-specs-pr/specification/nutanix/resource-manager/Microsoft.Nutanix/stable/2020-06-01
Associated swagger: /mnt/vss/_work/1/azure-rest-api-specs-pr/specification/nutanix/resource-manager/Microsoft.Nutanix/stable/2020-06-01/nutanix.json
{
  message: 'validateOperations - ErrorMessage:parameters is not iterable.ErrorStack:TypeError: parameters is not iterable\n' +
    '    at SwaggerExampleValidator.schemaIssuesToModelValidationIssues (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.38/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:347298:33)\n' +
    '    at SwaggerExampleValidator.validateRequest (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.38/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:347212:14)\n' +
    '    at SwaggerExampleValidator.validateOperation (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.38/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:347032:18)\n' +
    '    at onOperation (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.38/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:346997:36)\n' +
    '    at Object.exports.traverseSwaggerAsync (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.38/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:349499:54)\n' +
    '    at async SwaggerExampleValidator.validateOperations (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.38/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:346986:13)\n' +
    '    at async NewModelValidator.validateOperations (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.38/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:347413:9)\n' +
    '    at async /mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.38/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:352537:13\n' +
    '    at async Object.runScript [as run] (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.38/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:476650:28)\n' +
    '    at async main (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.38/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:476368:9)',
  level: '\x1B[31merror\x1B[39m'
}

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1847618&view=logs&j=14c5c170-9612-5b44-a650-13d3ca524cf8&t=a1928b1b-77e4-58b6-0247-4cedb38901b4

**Comment by ankhyk** [comment]
Hi @vw52 , this issue was fixed in https://github.com/Azure/oav/pull/855
We have not yet released version 3.0.5, you can install oav@beta and test it locally.

**Comment by raych1** [comment]
The fix was released in oav@3.2.0
