### ISSUE TITLE
Path parameter with the value containing / doesn't match regex

### ISSUE THREAD

**Issue by vishrutshah** [Azure/oav#88]
[Path](https://github.com/AuxMon/azure-rest-api-specs/blob/8dbb73a463b232d1c641d850aa1ed87f0993d44b/monitor/2016-03-01/swagger/metricDefinitions_API.json#L36): `"/{resourceUri}/providers/microsoft.insights/metricDefinitions"` does not match with the example:

https://github.com/AuxMon/azure-rest-api-specs/blob/8dbb73a463b232d1c641d850aa1ed87f0993d44b/monitor/2016-03-01/swagger/metricDefinitions_API.json#L139

CI: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/219411316#L2186

Reason: Value of the paramter {resourceUri} is not expected to have `/` with creates subpaths.

**cc:**
@amarzavery @veronicagg

**Comment by veronicagg** [comment]
@amarzavery can't remember... have we addressed this?

**Comment by amarzavery** [comment]
yup and we have a test for it as well https://github.com/Azure/oav/blob/master/test/modelValidatorTests.js#L9

**Comment by veronicagg** [comment]
great, thanks, closing then!
