### ISSUE TITLE
init: Build the cache for lookup

### ISSUE THREAD

**Issue by amarzavery** [Azure/oav#89]
- Clone the azure-rest-api-specs repo at a specified location.
- Read all the swagger spec files and parse them
- Create an in memory cache for all the operations across all the swagger specs.
The structure should look something like this
```json5
{
  "api-version1": [ {opeationObject(Sway)}, {operationObject(sway)}, . .  ],
  "api-version2": [ {opeationObject(Sway)}, {operationObject(sway)}, . . ]
  . . .
}

**Comment by vishrutshah** [comment]
Completed
