### ISSUE TITLE
Incorrect validation for additionalProperties in derived model

### ISSUE THREAD

**Issue by raych1** [Azure/oav#936]
Model validation recognize a property defined in derived model as additional properties. 

This is an example PR: https://github.com/Azure/azure-rest-api-specs/pull/21555

**Comment by raych1** [comment]
This is a [PR](https://github.com/Azure/azure-rest-api-specs/pull/22087/files) to fix examples. But the previous PR with these defect examples passed model validation. Can you check if it's related to this issue?

**Comment by ankhyk** [comment]
Here's additionalProperties rule: 
> a. “additionalProperties”: {“type”: “object”} means any object type in value;
b. “additionalProperties”: {} or “additionalProperties”: true means any type in value.

For https://github.com/Azure/azure-rest-api-specs/pull/21555, we can change the value of [additionalProperties](https://github.com/Azure/azure-rest-api-specs/blob/46b479ed48324a47691938ae4c10ba4fd88f2ec4/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/preview/2022-11-15-preview/services.json#L303:31) to `true` to accept any type properties

**Comment by raych1** [comment]
The PR in this issue has right behavior for model validation.
