### ISSUE TITLE
Incorrect payload file path in html report

### ISSUE THREAD

**Issue by leniatgh** [Azure/oav#947]
![Image](https://user-images.githubusercontent.com/4636380/211251109-d499a15d-3c63-43fb-8f9c-dd049cba0886.png)
The path of payload in html report should be relative with the report path.

_Originally posted by @tianxchen-ms in https://github.com/Azure/oav/issues/938#issuecomment-1375168228_

**Comment by leniatgh** [comment]
> If set `overrideLinkInReport` true, the payload path will be `payloadLinkPrefix` + file name.
> 
> If I have multiple folders and generate html report in `api_scenario_test_output/report/report.html`. I don't know how to set `payloadLinkPrefix`
> 
> ```
> api_scenario_test_output/report/recordings/OrAXPEIzPs/specification/appconfiguration/resource-manager/Microsoft.AppConfiguration/stable/2022-05-01/scenarios/recordings
> api_scenario_test_output/report/recordings/OyTNLqVk73/specification/appconfiguration/data-plane/Microsoft.AppConfiguration/stable/1.0/scenarios/recordings
> ```
> 
> Or can only override the swagger link and resolve payload path with report path?

Originally posted by @tianxchen-ms in https://github.com/Azure/oav/issues/938#issuecomment-1375173910

**Comment by raych1** [comment]
Fixed.
