### ISSUE TITLE
Breaking change in 3.2.3 to require "node >=16.18.1"

### ISSUE THREAD

**Issue by mikeharder** [Azure/oav#949]
In https://github.com/Azure/oav/pull/910, the engines section was changed from:

https://github.com/Azure/oav/blob/4e297241a62c4006fabf3bc1b8d692db4cada959/package.json#L133-L135

to:

https://github.com/Azure/oav/blob/476efaa6e98700236d25579996ceab01898e2f01/package.json#L133-L135

Changing the required Node version is usually considered a breaking change, and should only be done when shipping a new major version.

Currently, any customers depending on `oav@^3` (even transitively), and using a Node version older than `16.18.1` are broken.

I recommend:

* Deprecate `oav@3.2.3`
* Revert the `engines` section, and publish `oav@3.2.4`
* If you need to increase the required Node version, do so in `oav@4.0.0`

**Comment by weshaggard** [comment]
@raych1 this is also related to the other dependency issue that we should try and fix.

**Comment by raych1** [comment]
It cannot revert to node 10 as it doesn't support `matchAll` that was introduced by previous PR[#804](https://github.com/Azure/oav/pull/804/files). 

@mikeharder @weshaggard 
I think it should be fine with setting it to node 12 in [PR#952](https://github.com/Azure/oav/pull/952).  Let me know if it doesn't work.

**Comment by mikeharder** [comment]
Some JS packages increment their major version when dropping support for any Node version, even Node versions that are EOL.  

Other JS packages only increment their minor/patch version when dropping support for a Node version that is EOL.  This can break customers or dependent packages still using the EOL Node version, but it's a tradeoff these packages are willing to make.  Customers can pin an older version if needed, but dependent packages using caret dependencies are broken forever.

Since `oav` doesn't have many dependents, dropping Node 10 in a patch version seems OK to me.

**Comment by raych1** [comment]
[oav@3.2.4](https://www.npmjs.com/package/oav/v/3.2.4) was released but I don't have permission to deprecate 3.2.3.

**Comment by mikeharder** [comment]
@raych1: Do you agree that 3.2.3 should be deprecated?  If so, my team should be able to do this on your behalf.
