### ISSUE TITLE
Change dependency from "swagger-parser" to "@apidevtools/swagger-parser"

### ISSUE THREAD

**Issue by mikeharder** [Azure/oav#950]
`oav` currently depends on `swagger-parser@^10.0.3`:

https://github.com/Azure/oav/blob/476efaa6e98700236d25579996ceab01898e2f01/package.json#L43

`swagger-parser` has been renamed to `@apidevtools/swagger-parser`, and up to version `10.0.3`, the versions were kept in sync:

```
$ npm show swagger-parser@^10.0.3 dependencies
{ '@apidevtools/swagger-parser': '10.0.3' }
```

However, the latest version of `@apidevtools/swagger-parser` is `10.1.0`, and there is no corresponding version of `swagger-parser`:

```
$ npm show swagger-parser version
10.0.3

$ npm show @apidevtools/swagger-parser version
10.1.0
```

I recommend `oav` should change its dependency from `swagger-parser@^10.0.3` to `@apidevtools/swagger-parser@^10.1.0`.

An important improvement in `@apidevtools/swagger-parser@10.1.0` is pinning the version of dependency `@apidevtools/json-schema-ref-parser`:

```
$ npm show @apidevtools/swagger-parser@10.0.3 dependencies
{
  '@apidevtools/json-schema-ref-parser': '^9.0.6',
  
$ npm show @apidevtools/swagger-parser@10.1.0 dependencies
{
  '@apidevtools/json-schema-ref-parser': '9.0.6',
```

**Comment by weshaggard** [comment]
@raych1 can you please get this work done as it has caused a number of issues in places where we consume this package.

**Comment by raych1** [comment]
@weshaggard , updated in [PR](https://github.com/Azure/oav/pull/952)

**Comment by raych1** [comment]
[oav@3.2.4](https://www.npmjs.com/package/oav/v/3.2.4) was released.
