### ISSUE TITLE
Multiple definitions have same value for x-ms-discriminator-value

### ISSUE THREAD

**Issue by koyasu221b** [Azure/oav#969]
I have a requirement to use the same x-ms-discriminator value to support polymorphism for generating the SDK. Specifically, I have one parent object called FeaturesItem and three child objects called ManeuverPointFeaturesItem, ViaWaypointFeaturesItem, and RoutePathFeaturesItem that extend the parent FeaturesItem object, but they use the same x-ms-discriminator type value. While the ova validate-spec example.json file passes, the ova-validate-example example.json file fails.

Reference.

- https://github.com/Azure/autorest/issues/3265

-  My [example commit](https://github.com/Azure/azure-rest-api-specs/commit/1d45da2507ed53bdb4cde734f008b0bf79fd62b7)

**Comment by konrad-jamrozik** [comment]
@koyasu221b I can assist with issues with the tooling related to spec validation, but for this I need following pieces of information:

- a link to a validation check by the tool that has failed;
- a review by swagger specification expert, confirming this is a problem with the tool, not with the spec itself.

Typically you can obtain these two by making a PR against azure-rest-api-specs (see [this doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/909/API-spec-PR-review) and parent doc) and getting a review from the auto-assigned reviewer.

If your case is different and making a PR to that repo doesn't apply, I still kindly ask you for additional details, including steps to reproduce the issue and confirmation by subject matter expert that the tooling is returning wrong validation failure.

**Comment by konrad-jamrozik** [comment]
This got solved, details here:
- https://github.com/Azure/azure-sdk-tools/issues/5836
