### ISSUE TITLE
Remove dependency on `ms-rest`

### ISSUE THREAD

**Issue by JackTn** [Azure/oav#972]
https://github.com/Azure/azure-rest-api-specs/issues/23530#issue-1664785862

**Comment by JackTn** [comment]
@mbashtovaya

**Comment by mbashtovaya** [comment]
The latest version of oav [3.2.6](https://www.npmjs.com/package/oav/v/3.2.6) is dependent on the package "request" that has been deprecated in 2020, which triggers https://github.com/advisories/GHSA-p8p7-x288-28g6.

It is a transitive dependency coming from node_modules/ms-rest 2.5.6.

**Comment by scbedd** [comment]
I ran into this as a result of trying to apply audit fixes for this package. You're all absolutely right and this issue should probably be retitled as 

> Replace deprecated dependency `request` with newer alternative

As that's what it'll take to actually solve this. 👍

**Comment by scbedd** [comment]
We use `msrest` in [exactly one place](https://github.com/Azure/oav/blob/92115cb0ce822dcfdb729abb0b0d30bfeeb8fd97/lib/templates/httpTemplate.ts#L10)

If we take a dependency on the new package `@azure/core-rest-pipeline` (which will be "the core rest package" going forward), we can adjust to instead consume `PipelineRequest` interface.

**Comment by mbashtovaya** [comment]
@scbedd any update on this? we have outstanding CVEs for a while that cannot be resolved.

**Comment by scbedd** [comment]
@mbashtovaya long overdue but a fix for this is merged from #995
