### ISSUE TITLE
Work to be done on Monday

### ISSUE THREAD

**Issue by amarzavery** [Azure/oav#98]
- [x] Integrate operation.validateRequest()
- [x] Integrate operation.validateResponse()
- [x] LiveValidator buildCache() and lookUP() methods should throw LiveValidationError objects.
- [x] Integrate oav into express and run it on localhost:1337

**Comment by amarzavery** [comment]
First two are done. Minor tweaks may be required after some discussion on Monday.

**Comment by vishrutshah** [comment]
All done. closing this task
