### ISSUE TITLE
oav example-validator incorrectly flags "writeOnly" property missing from response body

### ISSUE THREAD

**Issue by mikekistler** [Azure/oav#997]
oav issues an "OBJECT_MISSING_REQUIRED_PROPERTY" error for a response body property that has
```
  "x-ms-mutability": ["create", "update"]
```

Here's the oav output:
```
Error reported:

{
  code: 'OBJECT_MISSING_REQUIRED_PROPERTY',
  message: 'Missing required property: topSecret',
  schemaUrl: '/Users/mikekistler/Projects/mikekistler/oav-test/tsp-output/@azure-tools/typespec-autorest/openapi.json',
  exampleUrl: '/Users/mikekistler/Projects/mikekistler/oav-test/tsp-output/@azure-tools/typespec-autorest/CreateWidget.json',
  schemaPosition: { line: 94, column: 15 },
  schemaJsonPath: '#/required',
  examplePosition: undefined,
  exampleJsonPath: '$responses.200.body.topSecret',
  severity: 0,
  source: 'response',
  operationId: 'Widgets_Create',
  level: '\x1B[31merror\x1B[39m'
}
```

with a sibling "$ref".  Here's the complete property definition:
```
    "topSecret": {
      "$ref": "#/definitions/secret",
      "description": "A top secret value.",
      "x-ms-mutability": [
        "update",
        "create"
      ]
    },
```

A similar property defined "inline" -- without $ref -- is handled correctly.

Normally siblings next to $ref are supposed to be ignored, but autorest explicitly defines a set of exceptions to that rule for its processing:

https://github.com/Azure/autorest/blob/main/docs/openapi/howto/%24ref-siblings.md

The openapi and example files to recreate are attached. And note that these are generated from TypeSpec.

Related to https://github.com/Azure/azure-sdk-tools/issues/6840

[oav-bug.zip](https://github.com/Azure/oav/files/12445505/oav-bug.zip)

**Comment by scbedd** [comment]
Resolved by this #996
